### PR TITLE
Removed trailing spaces from various files.

### PR DESCRIPTION
**Pull request by karrots**
This will help clean up future patches. I used the program https://github.com/dlenski/wtf to remove trailing spaces and fix new lines at end of files. I suggest applying this before the other patches to make them a bit more readable.

What editor and what OS do you use when programming? Most can be configured to prevent this type of white space from showing up.

### CODE REVIEW

**Comment by karrots** [comment]
I realized I have `rerere` turned on for my git repo. So when I tested merging PR #5 on top of this patch it worked fine because I already fixed the issues once before. So if PR #5 doesn't cleanly merge after applying PR #4 let me know I'll make the rebase PR #5.

In other words don't close the PR I'll just update the PR after #4 is merged unless you want to do it locally in your repo.

**Comment by LowPowerLab** [comment]
Yup you were right, after merging the first set, this won't merge from here and I'm not sure how to use the command line merger, could you resubmit it after you get latest?

**Comment by karrots** [comment]
Done

**Comment by LowPowerLab** [comment]
Cool, many thanks for your contributions!

**Pull request merged**
