### PR TITLE
Convert to node.js app server.

### PR DESCRIPTION
**Pull request by karrots**
This PR contains two commits.

Commit 8025063 converts the application to a pure node.js application. run the application with `npm start` after running `npm install` to install dependencies listed in `package.json`. 

Most dependencies were updated in the `package.json` as well. I left serialport and nedb at their current versions. Both look like they have possible breaking changes. I'll let you evaluate the need for those changes. Nedb would be good to look at as it has a fix in the latest version that looks like it may fix issues people are seeing with losing data.

Commit 6917316 in this PR adds a Dockerfile and moves the database, SSL certs, and other items that need to persist across containers into a new directory labeled `data`. This will allow the data to persist across new docker image builds and restarts. This Dockerfile works with resin.io for easy deployment to a favorite Raspberry Pi. I also use it on my regular desktop.

### CODE REVIEW

**Comment by karrots** [comment]
I realized this PR is missing one thing. I didn't modify the README.md or other files of that nature. I'll gladly add to this PR those changes as well. It may take a day or two to get around to it though.

**Comment by LowPowerLab** [comment]
Thanks for the valuable work you put into this, I will carefully review and test everything to ensure the published repo is a working copy. It will surely take some time.

**Comment by LowPowerLab** [comment]
FYI - as of NeDB 1.4.0 (updated via npm) it does not fix the database loss issue. I see in dev they are at 1.4.2 so did you refer to those newer changes?

**Comment by karrots** [comment]
I just looked at the changelog. The change in 1.4.1 looked like it might be the cause of issues.

https://github.com/louischatriot/nedb/wiki/Change-log

**Comment by LowPowerLab** [comment]
I just tried the latest NeDB 1.4.2 and it still will purge the file upon power loss.

**Comment by karrots** [comment]
Dang

**Comment by LowPowerLab** [comment]
Yup, I submitted an issue: https://github.com/louischatriot/nedb/issues/330
Maybe you could try it as well and see if you're getting the same thing?
I just manually copied the master ZIP content and did a npm install in the nedb directory to install dependencies. The database is still purged if I pull the plug.

**Comment by karrots** [comment]
Currently running my setup as a docker container on a regular PC. I need to get some things moved around before I can get at my RPi to do dev work on it.

I'll try _pulling the power_ on the docker container and see if it does the same. It might take a day or two to get around to it.

**Comment by LowPowerLab** [comment]
Finally I was able to test this. It works .. however I think I will need some help with setting up express to redirect HTTP to HTTPS and without the need to run at a random port. 
After the install if I just type the IP of the Pi it will time out. I have to specifically open it at something like: https://192.168.0.107:7443/
Then it asks for the credentials and loads the interface. Router port forwarding has to simply redirect port 80 to the internal IP at port 80, the rest should be taken care of the redirect, that's how it worked previously and was very transparent.
FWIW the npm install took a LONG time to setup the dependency tree.
FWIW2 neDB master is now stable and fixes the purging issue, now if he would just publish that to npm also ... but we're making a little progress at least, I like the express solution, makes it leaner :)
Thanks for your contributions!

**Comment by karrots** [comment]
So you want something listening on a non-SSL enabled port that does a
redirect to the HTTPS port. In your setup do you port forward the same port
on the outside as inside? so 7443 outside to 7443 inside?

Personally I don't do any port forwarding as I prefer to not expose stuff
like this. I VPN or SSH port forward when I do want to access. My bookmarks
go directly to the ports in question.

I do know what your talking about though. At work in our load balancers we
do the http->https redirects along with HSTS.

**Comment by LowPowerLab** [comment]
Well previously I was forwarding ports 80 and 443, which is not really ideal but allows easy loading of the interface via the external IP. Anyone can just use some security by obscurity there and change those external ports.
BUT I would like the internal ports to be 80 and 443, as traditionally. And also I'd like port 80 to redirect to 443 automatically, that was a nice feature I could use in nginx. If you know how to do that in express let me know, otherwise I can try to google around for a solution..
Also will need to figure out whats the best way to have gateway.js started at boot and kept going in case of failure. Right now I'm using upstart to do just that, if you have other suggestions let me know. Here's my documentation of how I setup upstart: https://lowpowerlab.com/gateway/#sourcecode

**Comment by LowPowerLab** [comment]
PS. I will plan to merge this pull once neDB pushes their fixes to NPM and also all these small details are ironed out. Just trying to make it as easy as Pi for folks to install on their Pis.
Some people suggest keeping a real webserver in front of node is good since it may deal better with DDOS and other attacks... what's your experience?
(I still like the express only solution though).

**Comment by karrots** [comment]
All my node.js experience is behind a firewall. Personally unless you're
limiting connections via the proxy it's not going to help. If the proxy is
running on the RPi it's probably going to die the same death anyway.

I haven't run node on port 80/443 as that would require running as root. I
haven't looked into dropping privileges like apache and nginx do either.
Nothing saying a proxy can't still be used with this setup. You would just
leave the node.js application running on the high ports and used nginx or
Apache in a similar way as your existing setup.

My suggestion is to provide systemd startup scripts for straight node.js
application. Sample configs for nginx for those who may wish to mix this
with an existing install. The reason I mention systemd is it's now the
preferred process manager in Ubuntu and Debian.

I also run my gateway on my regular PC in a Docker container at the moment.
I plan to deploy to the RPi after I move my wife's fish tank monitoring to
something else. My plan was to use resin.io to make image management easy.
Its also a quicker compile of all the npm modules due to the compile being
run in a VM and the inherent caching of Docker images. Hence the Dockerfile
add in the PR. The fish tank app is deployed this way it's pretty slick.

I have some further changes I may code up here soon that will make
deploying a bit easier. It centers around using the config module for
configuration management.

If you want to merge my PR into a separate branch for now that would work
as well. It would allow development to continue there then merge or
fast-forward the changes into master when things are to your liking. If you
need help with the git commands to make that happen let me know I'll send
you over the steps.

**Comment by karrots** [comment]
Added a couple more commits to start addressing the issues you mentioned.
- [x] systemd startup file
- [x] http to https redirect
- [x] Drop privileges after startup to allow binding on privileged ports

**Comment by LowPowerLab** [comment]
Great, I've tried the http>https myself with express-sslify but not much luck, then I saw your commit :)
I would like to run on ports 80 and 443 since this will be internal and people will need to port forward anyway so they can obscure there if they want to. Not sure if this is your third checkbox or that's something else.
Also does systemd work on debian? I will make an image with all these changes and that's based on raspbian (debian for Pi).
And last point, it's moteino not motenio, sorry for my weird naming, nobody can spell it :P.
I'll have to find some time tonight or maybe tomorrow to try these out. Thanks!

**Comment by karrots** [comment]
Dang I knew I was going to misspell it somewhere important. That's what I get for coding while sick.

Systemd was made the default init daemon in [version 8 of Debian(jessie)](https://www.debian.org/releases/stable/i386/release-notes/ch-whats-new.en.html#systemd) & [15.04 of Ubuntu](https://wiki.ubuntu.com/SystemdForUpstartUsers)

Only a couple of lines to add to get the privilege dropping working.

**Comment by karrots** [comment]
Ok fixed the misspellings and added the dropping of privileges. 

For the privilege changing to work you will need to create (or reuse) a user and group for the application to use. I moved the opening of the serial port to the portion of code while the program is root. So opening the serial port shouldn't be an issue.

Ports are defined in the settings so folks can change them at will. They can also be set with environment variables.

**Comment by LowPowerLab** [comment]
I tried the dropping of privileges code with a moteino/moteino group I just created. First thing I noticed after creating the new u+g is that node command was not found (bash: node: command not found), weird but reboot fixed it. Second is that starting "node gateway.js &" (with user pi) throws this error:

Error: listen EACCES
pointing to this line: http.createServer(httpApp).listen(httpApp.get('port'), function() {

Sounds like some access rights error. I also tries to just force express to run on 80/443 but I see the same error. Any way to just run on 80/443 without jumping these hoops? If the starting user is root how come this error happens?
Or am I doing it wrong? I didnt add the systemd changes, I just wanted to incrementally try all your changes. I'd like to be able to manually start/stop gateway when needed so this is a good exercise.

**Comment by karrots** [comment]
To bind to ports below 1024 the application must be started as root. Hence
the reason for dropping privilege.

You'll need to start the app as root with `sudo` or `su`.

**Comment by LowPowerLab** [comment]
Ok so I can start using "sudo su" then invoking "/opt/node/bin/node gateway.js &"
The problem I run into now is as soon as the webserver starts it will throw this:
Error: EACCES, open '/home/pi/gateway/data/db/gateway.db'
So I think it's some file access issue, the new user might not have access to that?

**Comment by LowPowerLab** [comment]
OK i was able to give r+w permissions to all others using chmod (sudo chmod -R ugo+rw /home/pi/gateway/data/db), now it does everything I want, native port 80 to 443 redirect.
My remaining question is whether these permissions are safe. If the user is changed from root to moteino, then user/group moteino has to have write permissions to the db directory. After my changes the /gateway/data/db permissions are: drwxrwxrwx 2 pi pi

**Comment by karrots** [comment]
Permissions should be rwxr--r-- allowing read to everyone but only write to the moteino user. Another valid permission level would be rwxrwxr-- giving the user and group full access but everyone only read. The everyone permission level depends on how secure the box is. If its just a home users having read access to the directory would be ok but not needed.

You can start the application with out starting a shell using the following command.

`sudo /opt/node/bin/node gateway.js &`

You can start a shell with `sudo -s`

**Comment by LowPowerLab** [comment]
Ok after messing around with chown/chmod I managed to change the permissions and now it looks like this (sudo ls -ld):
drwxr--r-- 2 moteino pi
It works, but I cannot access the db folder over FTP with user pi, I think I'm doing something wrong.
Could you recommend a set of A-to-Z commands to create the new user/group, set the permissions for the gateway and still allow pi to read/write the db folder? That would save me so much googling :)
If there's a simpler way to do it I'm all for it, in the end this will go into the public's hands, they will need to understand how it's setup and how to change the moteino password to make it secure etc.

**Comment by karrots** [comment]
Yea i'll look into it tonight. Running as the 'pi' user could you send the
output of the 'id' command.

**Comment by LowPowerLab** [comment]
Here it is:
uid=1000(pi) gid=1000(pi) groups=1000(pi),4(adm),20(dialout),24(cdrom),27(sudo),29(audio),44(video),46(plugdev),60(games),100(users),106(netdev),996(gpio),997(i2c),998(spi),999(input)

**Comment by karrots** [comment]
Ok there are three options.
1. Change the application to use the `pi` user and group when it drops privileges. 
   - In the new settings format this can be done by editing the default.json5 file in the repo if you think this should be a default for everyone or leave the repo the way it is and add a [local.json5](https://gist.github.com/karrots/cc4e2a0e6845ff3acab0) to your build with the user and group overridden.
   - In the settings.js change the user and group to `pi`.
2. Add a password to the `motenio` user and use that username to scp/sftp(more flexible and secure than straight ftp) and grab the DB that way.
3. Add the `pi` user to the `moteino` group and setup permissions appropriate for that group.

``` bash
#Add pi user to moteino group. 
adduser pi moteino
#Change permissions to rwxrwx--- on directory.
chmod 770 /path/to/db/dir
#Make sure directory is owned by moteino user and group
chown -R moteino:moteino /path/to/db/dir
```

**Comment by LowPowerLab** [comment]
I gave #3 a quick try, still didn't work, so I will go with Option #1, which is no different than in the past. 
Next I have to check out your settings changes.
Getting closer...

**Comment by karrots** [comment]
Sorry my commands on 3 weren't a full one stop shop. It was tailored for an existing install. Either way option 1 is probably the best in your prebuilt image scenario.

Once your comfortable with where the config change branch is at. I can change the default user/group and anything else before the merge and squash the changes into a smaller number of commits before merging. It will make for a cleaner history.

**Comment by LowPowerLab** [comment]
Just got back to working through this pull after a long break. I am trying to systemd changes but I ran into some snags, apparently [systemd is not installed on raspbian according to this article](http://blog.higgsboson.tk/2012/09/19/systemd-on-raspbian/). It also suggests that once installed systemd will need to be switched over from the init startup system. Suggestions?

**Comment by LowPowerLab** [comment]
Update: I managed to `sudo apt-get install systemd`. Then `sudo systemctl daemon-reload` worked. However `sudo systemctl start moteino-gateway` gives me a `Failed to issue method call: Unit name moteino-gateway is not valid.` message.

**Comment by karrots** [comment]
This article is from 3 years ago. Debian has since switched in Jessie to systemd for its init system. You'll need to update your rasbian install to a Jessie based version.

See my previous comment on the subject.

https://github.com/LowPowerLab/RaspberryPi-Gateway/pull/6#issuecomment-159734994

**Comment by LowPowerLab** [comment]
Thanks! Totally missed that now and previously I didn't make the connection. I will try this tomorrow.

**Comment by karrots** [comment]
Did you place the service file in '/etc/systemd/system/'?

**Comment by LowPowerLab** [comment]
Yup I did, then I rebooted and ran `sudo systemctl daemon-reload` which didn't give any message, then `sudo systemctl start moteino-gateway` failed with that msg.

**Comment by karrots** [comment]
I tested in Ubuntu I'll check if Debian needs the file in a different location.

**Comment by karrots** [comment]
Still need to verify but it looks like it should be `/lib/systemd/system/`

**Comment by LowPowerLab** [comment]
I moved the service file to `/lib/systemd/system/` and called the 2 commands again, same outcome. I wonder if rights has anything to do with it, some service files in the same dir have different rights. My fear of switching to jessie is that many commands might be different from what the user base got used to..I could be wrong about that though. I noticed your node is in `/usr/bin/nodejs`, mine is in `/opt/node/bin/node`.
FWIW I noticed a significant boost in startup/reboot time after the switch to systemd.

**Comment by karrots** [comment]
Are you running the commands as root? You'll need to be root to run any
systemd commands.

**Comment by LowPowerLab** [comment]
Yup all were sudo prepended

**Comment by karrots** [comment]
What happens when you type `systemctl list-unit-files moteino*`? I put my file in `/usr/systemd/system/` on a Debian Jessie install and it finds the file just fine.

**Comment by LowPowerLab** [comment]
I don't have a /usr/systemd/system folder, only a /etc/systemd/system and /lib/systemd/system
I tried it all over with the file in each location, same outcome.
Running `systemctl list-unit-files moteino*` gives this message: `Invalid number of arguments.`

**Comment by karrots** [comment]
Sorry `/lib/systemd/system` is correct. I miss typed.

Try `systemctl list-unit-files` and see if you get a similar error.

**Comment by LowPowerLab** [comment]
This gives me a multi page listing with `moteino-gateway.service` somewhere in the middle of the list with `disabled` in red, next to it.
(Just to recap, the service file is now in `/lib/systemd/system/` and I ran `sudo systemctl daemon-reload`   after I moved it there.)

**Comment by karrots** [comment]
Looks like systemd is aware of the unit file. Enabling it will allow start on startup.

**Comment by LowPowerLab** [comment]
Sorry but I'm not familiar with unit files :P
How might I enable it?

**Comment by karrots** [comment]
`systemctl enable <service name>` 

https://wiki.debian.org/systemd#Managing_services_with_systemd

**Comment by LowPowerLab** [comment]
That worked, thanks, the service now shows as `enabled`.
Also I noticed that I have to call `sudo systemctl start moteino-gateway.service` with the .service suffix, and that started the gateway app, otherwise it would still give the invalid argument error :)
Does the file have to have a .service suffix?

**Comment by karrots** [comment]
The .service part is system specific from what I read. Some require it
others don't.

**Comment by LowPowerLab** [comment]
Interesting.
Ok... I noticed that after a reboot/shutdown the service is automatically started.
Now I see that if i invoke a `stop`, it will still automatically start after a reboot. So I guess `enable` will make it run at reboots like you mentioned in the readme, and disable would stop auto-restarting. Cool stuff, the `systemctl restart ..` will be useful for code changes. Thanks for bearing with me through all this.

**Comment by LowPowerLab** [comment]
Do you know how we could redirect the `gateway.js` console output to a local file like it was done with upstart?
Calling `systemctl status moteino-gateway.service` will dump the last 10 lines to the screen :P

**Comment by karrots** [comment]
The service file already sends `stdout` and `stderr` to `syslog`. I have a foggy memory that the last ten line thing is something systemd does when invoked interactively. Did your process start successfully or was there an error? Let me look into it a bit more.

**Comment by LowPowerLab** [comment]
I read a bit about syslog and journal but it loosk like any commands I tried are not available on wheezy. People will ask for a way to download the logs of the moteino-gateway.service, and on a few occasions I wanted that as well so I could grep for certain things. Since I'm not very linux versed I get by easier in windows for such tasks. Hence the need for a way to get the log.
Also currently the gateway.js script will produce a lot of log, so it may be good to have a way to flush it from time to time.

**Comment by LowPowerLab** [comment]
Alternatively, could we make the gateway.js independently log output to a local file through a package maybe?
Still it would be nice to have the output dumped on the screen if the script is started manually. I think that's where it gets tricky.

**Comment by karrots** [comment]
We can change the redirect from syslog to a file for now.  The best thing long term would be to only output to stderr when there is an error or in debug mode. Do logging internally to the application.

**Comment by LowPowerLab** [comment]
Ok, how can we do the redirect for now?

**Comment by LowPowerLab** [comment]
Maybe unrelated but it looks like express is throwing exceptions at random times, I think it's always the same exception, complains it can't find the jade module but it's there in the node_modules dir, any suggestions?

`Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: [41B blob data]
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: [12-18-15_04:09:44.126] [ERROR] Error: Cannot find module 'jade'
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at Function.Module._resolveFilename (module.js:338:15)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at Function.Module._load (module.js:280:25)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at Module.require (module.js:364:17)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at require (module.js:380:17)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at new View (/home/pi/gateway/node_modules/express/lib/view.js:78:30)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at EventEmitter.render (/home/pi/gateway/node_modules/express/lib/application.js:569:12)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at ServerResponse.render (/home/pi/gateway/node_modules/express/lib/response.js:961:7)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at httpApp.get.hostpart (/home/pi/gateway/gateway.js:139:9)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at Layer.handle_error (/home/pi/gateway/node_modules/express/lib/router/layer.js:71:5)
Dec 18 04:09:44 raspberrypi2 moteino-Gateway[587]: at trim_prefix (/home/pi/gateway/node_modules/express/lib/router/index.js:310:13)`

**Comment by LowPowerLab** [comment]
How can i get in contact with you where we can have a better comm channel rather than this comments page? Can you email me at felix at lowpowerlab ?

**Comment by karrots** [comment]
You should have an email from me in your inbox now.

As for the jade issue unsure there. Try running `npm install` again from the `/home/pi/gateway` folder. Does the error happen when you manually run the program as well as with the systemd startup script?

On the logging front I'll setup the systemd unit file to direct the log to the same place you have the upstart logs going. I'll push a new commit to this PR.

**Comment by karrots** [comment]
I have reworked this onto current master with all the previous changes. I am also working on a _install_ script to make testing easier on my RPi. I'll create a new PR once that is done.

**Pull request closed without merging**
